env:
  browser: true
  es6: true
  jest: true
parser: "@typescript-eslint/parser"
plugins:
  - "react"
  - "@typescript-eslint"
  - "prettier"
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
parserOptions:
  ecmaVersion: 2019
  sourceType: "module"
settings:
  react:
    pragma: "React"
    version: "detect"
rules:
  "react/prop-types": 0
