stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - nvm install 10.6 --no-progress
    - nvm use 10.6

build:
  stage: build
  script:
    - npm i --no-progress --unsafe-perm
    - npm run build
  artifacts:
    paths:
      - dist/

# deploy-qa:
#     stage: deploy
#     script:
#         - echo "Deploying"
#         - ls -lah
#         - scp -rp ./dist/* someone@some_domain:some_dir
#     only:
#         - /^release*.*/
#         - master
#     environment:
#         name: qa
#         url: https://domain

# deploy-production:
#     stage: deploy
#     script:
#         - echo "Deploying"
#         - ls -lah
#         - scp -rp ./dist/* user@domain:~/public_html
#     only:
#         - master
#     environment:
#         name: production
#         url: https://domain
