stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - nvm install 10.6 --no-progress
    - nvm use 10.6

build:
  stage: build
  script:
    - npm i --no-progress --unsafe-perm
    - npm run build
  artifacts:
    paths:
      - dist/

# deploy-qa:
#     stage: deploy
#     script:
#         - echo "Deploying"
#         - ls -lah
#         - scp -rp ./dist/* $SERVER_QA_USER@$SERVER_QA_DOMAIN:SERVER_QA_DIRECTORY
#     only:
#         - /^release*.*/
#         - master
#     environment:
#         name: qa
#         url: https://$SERVER_QA_DOMAIN

# deploy-production:
#     stage: deploy
#     script:
#         - echo "Deploying"
#         - ls -lah
#         - scp -rp ./dist/* $SERVER_PROD_USER@$SERVER_PROD_DOMAIN:SERVER_PROD_DIRECTORY
#     only:
#         - master
#     environment:
#         name: production
#         url: https://SERVER_PROD_DOMAIN
