name: static-site

proxy:
  appserver:
    - website.lndo.site:8000

services:
  appserver:
    type: node:11
    globals:
      gatsby-cli: latest
      yarn: latest
    port:
      - 8000
    run:
      - echo "Installing Gatsby with yarn"
      - yarn

events:
  post-start:
    - appserver: yarn build

tooling:
  gatsby:
    service: appserver
  node:
    service: appserver
  npm:
    service: appserver
  npx:
    service: appserver
  yarn:
    service: appserver
