name: gatsby

proxy:
  appserver:
    - gatsby.lndo.site

services:
  appserver:
    type: node:11
    globals:
      yarn: latest
    build:
      - echo "\nClearing old node_modules..." && rm -rf node_modules && echo "Done!"
      - echo "\nInstalling Gatsby with yarn" && yarn
    command:
      - yarn develop -H 0.0.0.0 -p 80

tooling:
  node:
    service: appserver
  npm:
    cmd: Nope, try `lando yarn` instead.
    service: appserver
  npx:
    service: appserver
  yarn:
    service: appserver
  gatsby:start:
    cmd: yarn develop -H 0.0.0.0 -p 80
    service: appserver
