name: gatsby

proxy:
  appserver:
    - gatsby.lndo.site

services:
  appserver:
    type: node:13
    globals:
      yarn: latest
    build-as-root:
      - apk update && apk upgrade
      # - apt install -y https://alpine.pkgs.org/edge/alpine-main-x86/git-2.26.2-r0.apk.html
    build:
      - yarn --force
    overrides:
      image: node:13-alpine

tooling:
  node:
    service: appserver
  npm:
    cmd: Nope, try `lando yarn` instead.
    service: appserver
  npx:
    service: appserver
  yarn:
    service: appserver
    user: root
  develop:
    cmd: yarn develop -H 0.0.0.0 -p 80
    service: appserver
    user: root
