deploy:qa:
  extends: .set_up_ssh
  stage: deploy
  environment:
    name: QA
    url: $SERVER_HOST_QA
  only:
    - master
  script:
    - apt-get update
    - apt-get install rsync -y
    - rsync -rv ./public/* "$SERVER_USERNAME_QA@$SERVER_HOST_QA:$SERVER_DIR_QA"
